### ISSUE TITLE
Pivotal Tracker generates a CSV incompatible with our importing mechanism

### ISSUE THREAD

**Issue by mateusdeap** [fastruby/points#72]
**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

`main`. This bug is currently in production

**Expected behavior:**

Given a CSV file exported from Pivotal Tracker, when I click in Import/Export in points, add that file and click Import, it should generate all stories contained within the CSV in points

**Actual behavior:**

It give an error complaining of missing headers title, description and position

**Steps to reproduce:**

How do I achieve this behavior? Use the following format to provide a step-by-step guide:

1. Export a CSV from Pivotal Tracker with the stories you want
2. Go to the project's page in points and click Import/Export
3. Click to pick a file from your computer and add the CSV you exported from Pivotal Tracker
4. Click on "Import"

**Context and environment:**

This is all happening in production, currently. No special context needed except for a project you wish to add stories to.

**I will abide by the [code of conduct] (CODE_OF_CONDUCT.md)**
